# Custom Language File for Launcher Customizer

[ejs.app]
title = "FalloutRP Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/filflo1500000/FalloutRP"
mediaTwitterURL = "https://twitch.tv/filflo"
mediaInstagramURL = "#"
mediaYouTubeURL = "https://www.youtube.com/channel/UCN6FqRjwRjYBbHpXdRyESag"
mediaDiscordURL = "https://discord.gg/2qBK4AXdPb"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "Bienvenue sur FalloutRP"
welcomeDescription = "Fallout est une série de jeux vidéo de rôle se déroulant dans un univers post-apocalyptique. Elle a été créée par Interplay Entertainment et est actuellement développée par Bethesda Game Studios et éditée par Bethesda Softworks. La série est connue pour son style unique, mélangeant rétro-futurisme, humour noir et une ambiance de guerre froide des années 1950"
welcomeDescCTA = "Vous n'êtes qu'à quelques clics de FalloutRP."
