# Custom Language File for Launcher Customizer

[ejs.app]
title = "Fallout RP"

[ejs.landing]
mediaGitHubURL = "https://github.com/dscalzi/HeliosLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/2qBK4AXdPb"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "Bienvenue sur FalloutRP"
welcomeDescription = "notre but est de vous faire découvrir l'univers de Fallout à travers ce serveur RolePlay survivez rejoignez une faction ou créer votre petit groupe tout en parcourant les terres désolées de la Louisiane explorée et découvrir ce monde formidable où les expériences de vault tec font encore rage."
welcomeDescCTA = "Vous n'êtes qu'à quelques clics de FalloutRP."
